name: ci-workflow
on: [push, pull_request]
jobs:
    job:
        runs-on: ubuntu-latest
        timeout-minutes: 3
        strategy:
            matrix:
                node-version: [10.x]
        steps:
            - uses: actions/checkout@v1
              with:
                  submodules: true
            - name: Lint
              uses: mooyoul/tslint-actions@v1.1.1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  project: ${{ github.workspace }}/src/js/tslint.json
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
