name: ci-workflow
on: [push, pull_request]
jobs:
    job:
        runs-on: ubuntu-latest
        timeout-minutes: 3
        strategy:
            matrix:
                node-version: [10.x]
        steps:
            - uses: actions/checkout@v1
            - name: Lint
              uses: mooyoul/tslint-actions@v1.1.1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  project: $GITHUB_WORKSPACE/src/js
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
